# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:13
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=redactor.fields.RedactorField(blank=True, max_length=5000, null=True, verbose_name='Post Text'),
        ),
    ]
