# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 00:39
from __future__ import unicode_literals

import api_django_blog.extra
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=api_django_blog.extra.ContentTypeRestrictedFileField(help_text='JPEG, PNG, JPG, GIF - 10 Mb Max', null=True, upload_to='posts/thumbs'),
        ),
    ]
